apiVersion: ocm.software/v3alpha1
kind: ComponentVersion
metadata:
  name: github.com/sidhishruti22/frontend
  provider:
    name: sidhishruti22
  version: v1.0.4
repositoryContexts: []
spec:
  resources:
  - access:
      localReference: sha256.ee79c92bbcce9e7a98f07c6577fd56dd45cf6f7c2d3115216ee249f42119030e
      mediaType: application/yaml
      type: localBlob
    name: config
    relation: local
    type: configdata.ocm.software
    version: v1.0.4
  - access:
      imageReference: ghcr.io/stefanprodan/podinfo:6.3.3
      type: ociArtifact
    name: image
    relation: external
    type: ociImage
    version: 6.2.1
  - access:
      localReference: sha256.592329243c8b2f8ee7f177ebd9c0f03add6fdbe8cf091e857f3a36f87c40d682
      mediaType: application/x-tgz
      type: localBlob
    name: manifests
    relation: local
    type: kustomize.ocm.fluxcd.io
    version: v1.0.4
